-- =================================================================
-- SOPRA — Personnel seed data
-- Generated from HOMESTAY.docx personnel list (76 anggota)
-- Run this AFTER database_schema.sql has been imported, e.g.:
--   mysql -u root -p sopra_db < personnel_seed_data.sql
-- =================================================================

USE sopra_db;

INSERT INTO personnel (rank_name, name) VALUES
    ('DSP', 'Romeo'),
    ('SI/D', 'Mike'),
    ('KPL/D', 'Selong'),
    ('LANS KPL/D', 'Epeng'),
    ('ASP', 'Rembo'),
    ('SM/D', 'Rg'),
    ('KPL/D', 'Sofia'),
    ('LANS KPL/D', 'Iraq'),
    ('ASP', 'Rifle'),
    ('SM/D', 'Tc'),
    ('KPL/D', 'Aliaa'),
    ('LANS KPL/D', 'Sika'),
    ('ASP', 'Zuri'),
    ('SJN/D', 'Panther'),
    ('KPL/D', 'Upin'),
    ('LANS KPL/D', 'Tapai'),
    ('INSP', 'Gaza'),
    ('SJN/D', 'Sky'),
    ('KPL/D', 'Angah'),
    ('LANS KPL', 'Loloq'),
    ('INSP', 'Talam'),
    ('SJN/D', 'Mydeen'),
    ('KPL/D', 'Torres'),
    ('LANS KPL', 'Boron'),
    ('INSP', 'Poker'),
    ('SJN/D', 'Jedai'),
    ('KPL/D', 'Achai'),
    ('LANS KPL', 'Costa'),
    ('INSP', 'Wesley'),
    ('SJN/D', 'Godong'),
    ('KPL/D', 'Berry'),
    ('LANS KPL/D', 'Nippon'),
    ('INSP', 'Berlin'),
    ('SJN/D', 'Puma'),
    ('KPL/D', 'Kapit'),
    ('LANS KPL', 'Paco'),
    ('INSP', 'Nova'),
    ('SJN/D', 'Porro'),
    ('KPL/D', 'Damak'),
    ('LANS KPL', 'Veloz'),
    ('SJN/D', 'Che Mat'),
    ('KPL/D', 'Paktam'),
    ('LANS KPL/D', 'Usain'),
    ('KPL/D', 'Matic'),
    ('LANS KPL/D', 'T-Rex'),
    ('KPL/D', 'Dhalsim'),
    ('LANS KPL/D', 'Steve'),
    ('KPL/D', 'Tobi'),
    ('LANS KPL/D', 'Tugu'),
    ('KPL/D', 'Simon'),
    ('LANS KPL/D', 'Gambit'),
    ('KPL/D', 'Asun'),
    ('LANS KPL/D', 'Badang'),
    ('KPL/D', 'Lv'),
    ('LANS KPL', 'Tameng'),
    ('KPL/D', 'Nike'),
    ('LANS KPL/D', 'Thunder'),
    ('KPL/D', 'Buntat'),
    ('LANS KPL/D', 'Ghost'),
    ('KPL/D', 'Kedak'),
    ('LANS KPL/D', 'Nunez'),
    ('KPL/D', 'Gaban'),
    ('LANS KPL', 'Bilal'),
    ('KPL/D', 'Santa'),
    ('LANS KPL', 'Kapak'),
    ('KPL/D', 'Palong'),
    ('LANS KPL', 'Belut'),
    ('KPL/D', 'Rejang'),
    ('LANS KPL', 'Frankie'),
    ('KPL/D', 'Misi'),
    ('LANS KPL/D', 'Soccer'),
    ('LANS KPL/D', 'Daisy'),
    ('LANS KPL', 'Nana'),
    ('LANS KPL/D', 'Jerai'),
    ('LANS KPL', 'Pilah'),
    ('LANS KPL', 'Tenjo');
